GET http://localhost:3003/api/blogs/ HTTP/1.1

###
GET http://localhost:3003/api/users/ HTTP/1.1

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vybm1lIjoidGVzdGluZ2p3dCIsImlkIjoiNjViNjU4NTU5Mzk0ZWViOGIxMmNmNmNlIiwiaWF0IjoxNzA2NDQ5MDAzLCJleHAiOjE3MDY0NTI2MDN9.KOFzl1DSODRLnqnyDLTOrs_XI7LcIgwU2kaSEfTXO-M

{
    "title": "testing token middleware with VS rest client",
    "author": "James Author",
    "url": "http:?jauthor.com/rest-client",
    "likes": 600
}

###
PUT http://localhost:3003/api/blogs/65b4243750c647a1fe16618d HTTP/1.1
Content-Type: application/json

{
    "title": "Posting with VS rest client",
    "author": "James Author",
    "url": "http:?jauthor.com/rest-client",
    "likes": 600
}

###
DELETE http://localhost:3003/api/blogs/65b659483cbd061286f25b4a HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vybm1lIjoidGVzdGluZ2p3dCIsImlkIjoiNjViNjU4NTU5Mzk0ZWViOGIxMmNmNmNlIiwiaWF0IjoxNzA2NDQ5MDAzLCJleHAiOjE3MDY0NTI2MDN9.KOFzl1DSODRLnqnyDLTOrs_XI7LcIgwU2kaSEfTXO-M

###
GET http://localhost:3003/api/users/ HTTP/1.1

###
POST http://localhost:3003/api/users/ HTTP/1.1
Content-Type: application/json

{
    "username": "testingjwt",
    "name": "testing123",
    "password": "testingjwt1234"
}

###
POST http://localhost:3003/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "testingjwt",
    "password": "testingjwt1234"
}